stages:
  - deploy

variables:
  CONTAINER_NAME: botlikeauto
  EXTERNAL_PORT: 8376
  INTERNAL_PORT: 3000

deploy:
  stage: deploy
  script:
    - echo "Deploying via shell runner..."
    - docker stop $CONTAINER_NAME || true
    - docker rm $CONTAINER_NAME || true
    - docker build -t $CONTAINER_NAME .
    - docker run -d -p $EXTERNAL_PORT:$INTERNAL_PORT --name $CONTAINER_NAME $CONTAINER_NAME
    - echo "Deployment complete!"
  only:
    - dev
  tags:
    - dev_scouting
